/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        outline: '#849495',
        secondary: '#d7ffc5',
        'error-container': '#93000a',
        'tertiary-fixed': '#ffdbce',
        'secondary-container': '#2ff801',
        'surface-bright': '#37393e',
        'on-primary-fixed-variant': '#004f54',
        'on-error': '#690005',
        'on-tertiary': '#5a1c00',
        'outline-variant': '#3b494b',
        'on-tertiary-fixed-variant': '#7f2b00',
        'surface-container-lowest': '#0c0e12',
        'inverse-primary': '#006970',
        'secondary-fixed-dim': '#2ae500',
        'primary-fixed': '#7df4ff',
        'surface-container-high': '#282a2e',
        'on-secondary-container': '#0f6d00',
        'surface-variant': '#333539',
        'on-surface': '#e2e2e8',
        tertiary: '#fff3f0',
        'on-secondary-fixed': '#022100',
        background: '#111318',
        surface: '#111318',
        'on-error-container': '#ffdad6',
        'primary-container': '#00f0ff',
        'on-primary': '#00363a',
        'on-secondary': '#053900',
        'on-secondary-fixed-variant': '#095300',
        'on-background': '#e2e2e8',
        'surface-container-low': '#1a1c20',
        'primary-fixed-dim': '#00dbe9',
        'surface-container': '#1e2024',
        'on-tertiary-fixed': '#370e00',
        error: '#ffb4ab',
        'on-surface-variant': '#b9cacb',
        'tertiary-container': '#ffcfbd',
        primary: '#dbfcff',
        'tertiary-fixed-dim': '#ffb599',
        'inverse-on-surface': '#2f3035',
        'inverse-surface': '#e2e2e8',
        'surface-dim': '#111318',
        'on-tertiary-container': '#a63b00',
        'secondary-fixed': '#79ff5b',
        'on-primary-fixed': '#002022',
        'on-primary-container': '#006970',
        'surface-tint': '#00dbe9',
        'surface-container-highest': '#333539',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        sm: '16px',
        xs: '8px',
        md: '24px',
        'grid-gutter': '16px',
        base: '4px',
        lg: '32px',
        xl: '48px',
        'grid-margin': '24px',
      },
      fontFamily: {
        'body-md': ['Geist', 'sans-serif'],
        'display-lg': ['Space Grotesk', 'sans-serif'],
        'data-label': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'body-sm': ['Geist', 'sans-serif'],
        'data-value': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'data-label': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'data-value': ['18px', { lineHeight: '24px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
